-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- Insert Into questions(type,text) values
-- ('text', 'What is you name?'),
-- ('number', 'How old are you?'),
-- ('multiLine', 'How do you feel when you wake up in the mornings?'),
-- ('multiLine', 'Are you happy with you job?');
